use_frameworks!

platform :ios, '9.0'

target 'SMKeyboardObserber_Example' do
  pod 'SMKeyboardObserber', :path => '../'

  target 'SMKeyboardObserber_Tests' do
    inherit! :search_paths

    
  end
end
